/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Ventanas;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import proyecto.programacion.Animales;

public class AnimalP extends javax.swing.JDialog {

    DefaultTableModel modeloAnimales = new DefaultTableModel();
    Animales[] ArrayAnimales = new Animales[10];

    public AnimalP(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setTitle("Registro de Animales");
        this.setSize(570, 400);
        modeloAnimales.addColumn("Nombre");
        modeloAnimales.addColumn("Especie");
        modeloAnimales.addColumn("Edad");
        modeloAnimales.addColumn("Sexo");
        
        AnimalTb.setModel(modeloAnimales);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        AnimalTb = new javax.swing.JTable();
        NombreAnimal = new javax.swing.JLabel();
        EspecieAnimal = new javax.swing.JLabel();
        EdadAnimal = new javax.swing.JLabel();
        SexoAnimal = new javax.swing.JLabel();
        NombreAnimalField = new javax.swing.JTextField();
        EspecieAnimalField = new javax.swing.JTextField();
        EdadAnimalField = new javax.swing.JTextField();
        SexoAnimalCb = new javax.swing.JComboBox<>();
        AgregarAnimalBt = new javax.swing.JButton();
        EliminarAnimalBt = new javax.swing.JButton();
        EditarAnimalBt = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        AnimalTb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        AnimalTb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AnimalTbMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(AnimalTb);

        NombreAnimal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NombreAnimal.setText("Nombre");

        EspecieAnimal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        EspecieAnimal.setText("Especie");

        EdadAnimal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        EdadAnimal.setText("Edad");

        SexoAnimal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SexoAnimal.setText("Sexo");

        SexoAnimalCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Macho", "Hembra" }));

        AgregarAnimalBt.setText("Agregar");
        AgregarAnimalBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarAnimalBtActionPerformed(evt);
            }
        });

        EliminarAnimalBt.setText("Eliminar");
        EliminarAnimalBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarAnimalBtActionPerformed(evt);
            }
        });

        EditarAnimalBt.setText("Editar");
        EditarAnimalBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarAnimalBtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NombreAnimal)
                    .addComponent(EspecieAnimal)
                    .addComponent(EdadAnimal)
                    .addComponent(SexoAnimal))
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(NombreAnimalField)
                    .addComponent(EspecieAnimalField)
                    .addComponent(EdadAnimalField)
                    .addComponent(SexoAnimalCb, 0, 135, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EliminarAnimalBt)
                    .addComponent(EditarAnimalBt)
                    .addComponent(AgregarAnimalBt, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(30, 30, 30))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(AgregarAnimalBt))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(NombreAnimal)
                            .addComponent(NombreAnimalField, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EspecieAnimal)
                    .addComponent(EspecieAnimalField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EdadAnimal)
                    .addComponent(EdadAnimalField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EliminarAnimalBt))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SexoAnimalCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SexoAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(EditarAnimalBt)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void AgregarAnimalBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarAnimalBtActionPerformed

        Animales animal = new Animales();
        animal.setNombre(NombreAnimalField.getText());
        animal.setEspecie(EspecieAnimalField.getText());
        animal.setEdad(Integer.parseInt(EdadAnimalField.getText()));
        animal.setSexo(SexoAnimalCb.getSelectedItem().toString());

        for (int x = 0; x < ArrayAnimales.length; x++) {
            if (ArrayAnimales[x] == null) {
                ArrayAnimales[x] = animal;
                break;
            }

        }

        Object a[] = new Object[4];
        a[0] = animal.getNombre();
        a[1] = animal.getEspecie();
        a[2] = animal.getEdad();
        a[3] = animal.getSexo();
        
        modeloAnimales.addRow(a);

        AnimalTb.repaint();
        NombreAnimalField.setText("");
        EspecieAnimalField.setText("");
        EdadAnimalField.setText("");

    }//GEN-LAST:event_AgregarAnimalBtActionPerformed

    private void EliminarAnimalBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarAnimalBtActionPerformed
        int SelectedRowIndex=AnimalTb.getSelectedRow();
        modeloAnimales.removeRow(SelectedRowIndex);
        
    }//GEN-LAST:event_EliminarAnimalBtActionPerformed

    private void EditarAnimalBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarAnimalBtActionPerformed
        int i=AnimalTb.getSelectedRow();
        if (i >= 0){
            modeloAnimales.setValueAt(NombreAnimalField.getText(), i, 0);
            modeloAnimales.setValueAt(EspecieAnimalField.getText(), i, 1);
            modeloAnimales.setValueAt(EdadAnimalField.getText(), i, 2);
            modeloAnimales.setValueAt(SexoAnimalCb.getSelectedItem().toString(),i,3);
        }else{
            JOptionPane.showMessageDialog(null,"Error");
        }
    }//GEN-LAST:event_EditarAnimalBtActionPerformed

    private void AnimalTbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AnimalTbMouseClicked
        int SelectedRow=AnimalTb.getSelectedRow();
        NombreAnimalField.setText(modeloAnimales.getValueAt(SelectedRow, 0).toString());
        EspecieAnimalField.setText(modeloAnimales.getValueAt(SelectedRow, 1).toString());
        EdadAnimalField.setText(modeloAnimales.getValueAt(SelectedRow, 2).toString());
        
        
    }//GEN-LAST:event_AnimalTbMouseClicked

    public Animales[] getAnimales(){
        return this.ArrayAnimales;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnimalP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnimalP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnimalP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnimalP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AnimalP dialog = new AnimalP(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarAnimalBt;
    private javax.swing.JTable AnimalTb;
    private javax.swing.JLabel EdadAnimal;
    private javax.swing.JTextField EdadAnimalField;
    private javax.swing.JButton EditarAnimalBt;
    private javax.swing.JButton EliminarAnimalBt;
    private javax.swing.JLabel EspecieAnimal;
    private javax.swing.JTextField EspecieAnimalField;
    private javax.swing.JLabel NombreAnimal;
    private javax.swing.JTextField NombreAnimalField;
    private javax.swing.JLabel SexoAnimal;
    private javax.swing.JComboBox<String> SexoAnimalCb;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
