/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Ventanas;

import javax.swing.table.DefaultTableModel;


public class AnimalP extends javax.swing.JDialog {

    DefaultTableModel modelo=new DefaultTableModel();
    
    public AnimalP(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setTitle("Registro de Animales");
        this.setSize(720,570);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        AnimalTb = new javax.swing.JTable();
        NombreAnimal = new javax.swing.JLabel();
        EspecieAnimal = new javax.swing.JLabel();
        EdadAnimal = new javax.swing.JLabel();
        HabitatAnimal = new javax.swing.JLabel();
        SexoAnimal = new javax.swing.JLabel();
        NombreAnimalField = new javax.swing.JTextField();
        EspecieAnimalField = new javax.swing.JTextField();
        EdadAnimalField = new javax.swing.JTextField();
        HabitatAnimalCb = new javax.swing.JComboBox<>();
        SexoAnimalCb = new javax.swing.JComboBox<>();
        AgregarAnimalBt = new javax.swing.JButton();
        EliminarAnimalBt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        AnimalTb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(AnimalTb);

        NombreAnimal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NombreAnimal.setText("Nombre");

        EspecieAnimal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        EspecieAnimal.setText("Especie");

        EdadAnimal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        EdadAnimal.setText("Edad");

        HabitatAnimal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        HabitatAnimal.setText("Habitat");

        SexoAnimal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SexoAnimal.setText("Sexo");

        HabitatAnimalCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pradera", "Bosque", "Desierto", "Montana", "Marisma", "Sabana", "Region Polar", "Altiplano", "Quebrada", "Lago", "Pantano", "Rio", "Arrecife de Coral", "Oceano", "Playa" }));

        SexoAnimalCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Macho", "Hembra" }));

        AgregarAnimalBt.setText("Agregar");
        AgregarAnimalBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarAnimalBtActionPerformed(evt);
            }
        });

        EliminarAnimalBt.setText("Eliminar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NombreAnimal)
                    .addComponent(EspecieAnimal)
                    .addComponent(EdadAnimal)
                    .addComponent(HabitatAnimal)
                    .addComponent(SexoAnimal))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(NombreAnimalField)
                    .addComponent(EspecieAnimalField)
                    .addComponent(EdadAnimalField)
                    .addComponent(HabitatAnimalCb, 0, 135, Short.MAX_VALUE)
                    .addComponent(SexoAnimalCb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AgregarAnimalBt)
                    .addComponent(EliminarAnimalBt))
                .addGap(32, 32, 32))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(NombreAnimal)
                    .addComponent(NombreAnimalField, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EspecieAnimal)
                    .addComponent(EspecieAnimalField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AgregarAnimalBt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EdadAnimal)
                    .addComponent(EdadAnimalField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EliminarAnimalBt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HabitatAnimal)
                    .addComponent(HabitatAnimalCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SexoAnimal)
                    .addComponent(SexoAnimalCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AgregarAnimalBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarAnimalBtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AgregarAnimalBtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnimalP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnimalP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnimalP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnimalP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AnimalP dialog = new AnimalP(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarAnimalBt;
    private javax.swing.JTable AnimalTb;
    private javax.swing.JLabel EdadAnimal;
    private javax.swing.JTextField EdadAnimalField;
    private javax.swing.JButton EliminarAnimalBt;
    private javax.swing.JLabel EspecieAnimal;
    private javax.swing.JTextField EspecieAnimalField;
    private javax.swing.JLabel HabitatAnimal;
    private javax.swing.JComboBox<String> HabitatAnimalCb;
    private javax.swing.JLabel NombreAnimal;
    private javax.swing.JTextField NombreAnimalField;
    private javax.swing.JLabel SexoAnimal;
    private javax.swing.JComboBox<String> SexoAnimalCb;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
