/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Ventanas;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import proyecto.programacion.Visitantes;


public class VisitantesP extends javax.swing.JDialog {
        
    DefaultTableModel modeloVisitantes=new DefaultTableModel();
    Visitantes[] ArrayVisitantes=new Visitantes[10];
    
    /**
     * Creates new form VisitantesP
     */
    public VisitantesP(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setTitle("Registro de Visitantes");
        this.setSize(570,400);
        modeloVisitantes.addColumn("Nombre");
        modeloVisitantes.addColumn("Edad");
        modeloVisitantes.addColumn("Fecha de Ingreso"); 
        VisitantesTb.setModel(modeloVisitantes);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
   
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        VisitantesTb = new javax.swing.JTable();
        NombreVisitantes = new javax.swing.JLabel();
        EdadVisitantes = new javax.swing.JLabel();
        FechaVisitantes = new javax.swing.JLabel();
        NombreVisitantesField = new javax.swing.JTextField();
        EdadVisitantesField = new javax.swing.JTextField();
        FechaIngresoVisitantesField = new javax.swing.JTextField();
        AgregarVisitantesBt = new javax.swing.JButton();
        EliminarVisitantesBt = new javax.swing.JButton();
        EditarVisitantesBt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        VisitantesTb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        VisitantesTb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VisitantesTbMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(VisitantesTb);

        NombreVisitantes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        NombreVisitantes.setText("Nombre");

        EdadVisitantes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        EdadVisitantes.setText("Edad");

        FechaVisitantes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        FechaVisitantes.setText("Fecha Ingreso");

        NombreVisitantesField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreVisitantesFieldActionPerformed(evt);
            }
        });

        AgregarVisitantesBt.setText("Agregar");
        AgregarVisitantesBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarVisitantesBtActionPerformed(evt);
            }
        });

        EliminarVisitantesBt.setText("Eliminar");
        EliminarVisitantesBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarVisitantesBtActionPerformed(evt);
            }
        });

        EditarVisitantesBt.setText("Editar");
        EditarVisitantesBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarVisitantesBtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(FechaVisitantes)
                    .addComponent(EdadVisitantes, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NombreVisitantes, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(NombreVisitantesField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EdadVisitantesField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FechaIngresoVisitantesField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AgregarVisitantesBt)
                    .addComponent(EliminarVisitantesBt)
                    .addComponent(EditarVisitantesBt))
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(NombreVisitantes)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(NombreVisitantesField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(AgregarVisitantesBt)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EdadVisitantes)
                    .addComponent(EdadVisitantesField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EliminarVisitantesBt))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FechaVisitantes)
                            .addComponent(FechaIngresoVisitantesField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(EditarVisitantesBt)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NombreVisitantesFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreVisitantesFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreVisitantesFieldActionPerformed

    private void AgregarVisitantesBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarVisitantesBtActionPerformed
        Visitantes visitantes=new Visitantes();
        visitantes.setNombre(NombreVisitantesField.getText());
        visitantes.setEdad(Integer.parseInt(EdadVisitantesField.getText()));
        visitantes.setFechaIngreso(FechaIngresoVisitantesField.getText());
        
         for (int x = 0; x < ArrayVisitantes.length; x++) {
            if (ArrayVisitantes[x] == null) {
                ArrayVisitantes[x] = visitantes;
                break;
            }

        }
         
        Object objeto[] = new Object[3];
        objeto[0] = visitantes.getNombre();
        objeto[1] = visitantes.getEdad();
        objeto[2] = visitantes.getFechaIngreso();
        
        modeloVisitantes.addRow(objeto);

        VisitantesTb.repaint();
        NombreVisitantesField.setText("");
        EdadVisitantesField.setText("");
        FechaIngresoVisitantesField.setText("");
        
    }//GEN-LAST:event_AgregarVisitantesBtActionPerformed

    private void EditarVisitantesBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarVisitantesBtActionPerformed
       int i=VisitantesTb.getSelectedRow();
        if (i >= 0){
            modeloVisitantes.setValueAt(NombreVisitantesField.getText(),i,0);
            modeloVisitantes.setValueAt(EdadVisitantesField.getText(), i, 1);
            modeloVisitantes.setValueAt(FechaIngresoVisitantesField.getText(), i, 2);
            
        }else{
            JOptionPane.showMessageDialog(null,"Error");
        }
    }//GEN-LAST:event_EditarVisitantesBtActionPerformed

    private void EliminarVisitantesBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarVisitantesBtActionPerformed
        int SelectedRowIndex=VisitantesTb.getSelectedRow();
        modeloVisitantes.removeRow(SelectedRowIndex);
    }//GEN-LAST:event_EliminarVisitantesBtActionPerformed

    private void VisitantesTbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VisitantesTbMouseClicked
        int SelectedRow=VisitantesTb.getSelectedRow();
        NombreVisitantesField.setText(modeloVisitantes.getValueAt(SelectedRow, 0).toString());
        EdadVisitantesField.setText(modeloVisitantes.getValueAt(SelectedRow, 1).toString());
        FechaIngresoVisitantesField.setText(modeloVisitantes.getValueAt(SelectedRow, 2).toString());
        
    }//GEN-LAST:event_VisitantesTbMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VisitantesP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VisitantesP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VisitantesP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VisitantesP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VisitantesP dialog = new VisitantesP(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarVisitantesBt;
    private javax.swing.JLabel EdadVisitantes;
    private javax.swing.JTextField EdadVisitantesField;
    private javax.swing.JButton EditarVisitantesBt;
    private javax.swing.JButton EliminarVisitantesBt;
    private javax.swing.JTextField FechaIngresoVisitantesField;
    private javax.swing.JLabel FechaVisitantes;
    private javax.swing.JLabel NombreVisitantes;
    private javax.swing.JTextField NombreVisitantesField;
    private javax.swing.JTable VisitantesTb;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
